branches:
  only:
    - master
    - /\d+\.\d+\.x/

git:
  depth: false

dist: xenial

language: node_js
node_js: 12

cache:
  directories:
    - $HOME/.npm
    - $HOME/.sonar/cache
    - node_modules

env:
  - TEST_SUITE=lint
  - TEST_SUITE=build-storybook
  - TEST_SUITE=test-security
  - TEST_SUITE=test-unit
  - TEST_SUITE=pep8

before_install:
  - pip install --user pycodestyle

install:
  - npm install

script:
  - npm run $TEST_SUITE
  # - sonar-scanner
